const {
  ROUTEROS_ACCOUNTING_URL = "http://192.168.88.1/accounting/ip.cgi",
  INFLUX_MEASUREMENT = "accounting",
  IP_RANGE = "192.168.88.1-192.168.88.255",
  PUSH_INTERVAL = 1000,
  INFLUX_ADDRESS = "http://127.0.0.1:8086",
  INFLUX_DATABASE,
  INFLUX_RETENTION_POLICY,
  INFLUX_USERNAME,
  INFLUX_PASSWORD,
  INFLUX_CONSISTENCY,
} = process.env;

const CONFIG = {
  ROUTEROS_ACCOUNTING_URL,
  INFLUX_MEASUREMENT,
  IP_RANGE,
  PUSH_INTERVAL,
  INFLUX_ADDRESS,
  INFLUX_DATABASE,
  INFLUX_RETENTION_POLICY,
  INFLUX_USERNAME,
  INFLUX_PASSWORD,
  INFLUX_CONSISTENCY,
};

console.log("Config = %j", CONFIG);

exports = CONFIG;
